### ISSUE TITLE
PDP for stream

### ISSUE THREAD

**Issue by ldacey** [domoinc/domo-python-sdk#12]
When creating a stream, what is the best way to enable PDP? 

In the examples, the PDP settings are only within the 'Datasets' section and not the streams section. I was able to create a streaming dataset and then manually add PDP though using the UI at domo.com.

`pdp = datasets.create_pdp(dataset['id'], pdp_request)`

I tried to replace datasets with streams, but I received an error.

`pdp = streams.create_pdp(stream['id'], pdp_request)`

`AttributeError: 'StreamClient' object has no attribute 'create_pdp'`

**Comment by rswingler** [comment]
Thanks for asking! A Stream is an upload pipeline pointing to a specific DataSet, and is not a DataSet itself. Thus, a Stream ID is not a DataSet ID. Use streams.get to retrieve a Stream's metadata, which will contain the DataSet ID that Stream is pointing at:

https://github.com/domoinc/domo-python-sdk/blob/master/examples/stream.py#L30

Let me know if you have any other questions!

**Comment by ldacey** [comment]
I just realized that about 5 minutes after I posted my question but you responded before I could remove it. Thanks for your response.

As a follow up question:

What is the best approach for only showing rows for a specific user? One approach would be to create a separate PDP rule per employee by filtering for just the rows with that employee ID present and have that rule only be present for the corresponding Domo user ID, but that seems like it would be a lot (10s of thousands of employees).

```
    pdp_filter = PolicyFilter()
    pdp_filter.column = 'employee_id'
    pdp_filter.operator = FilterOperator.EQUALS
    pdp_filter.values = ['company_employee_id']  
    pdp_request = Policy()
    pdp_request.name = 'Only show data for the specific employee'
    pdp_request.filters = [pdp_filter]
    pdp_request.type = PolicyType.USER
    pdp_request.users = [domo_user_id]
```

**Comment by rswingler** [comment]
The best way is to apply the PDP to the general user group (everyone). This takes user management out of the equation with PDPs. To get familiar, use the Domo front end to create a PDP policy on a test dataset. When you add users to the PDP, search "everyone" and you'll see an "EV" icon. To do this via the API/SDKs, you'll need to identify the group ID for the "everyone" group. Also, the negation "NOT" parameter will be important: for example, I added a filter for a specific column and row value. To hide that row/value, use the negation "NOT" on the PDP policy (the negation parameter appears to be missing from the Domo front end). Without the negation, "everyone" would only see the exact value you specified (hiding everything else).

In addition, I you can add a second PDP policy to enable a few users to have full access to the dataset.

**Comment by ldacey** [comment]
Yes, I created a PDP policy using the UI to start with. 

The purpose is to only allow a person to see their own personal data, as indicated by an 'employee_id' field. It seems like when I create a Policy, it only allows me to select a column and then a value (or multiple values). So if I have 100 employees who only can see their own data, do I need to make 100 separate PDP policies? 

```
Policy Name:
Employee Filter

Data Access:
employee_id: xyzxyz

Groups & People:
ldacey
```

In the UI, that appeared to give me the intended behavior. When I went to the page, I was able **only** able to see data for employee xyzxyz. This seems like I would need to make a PDP policy per individual correct?

(This was a request I received, I am just seeing what the capabilities are. If it is not feasible then I will have to convince the team to change the PDP policies to something a little less strict compared to per employee).

**Comment by rswingler** [comment]
That is correct, your use case would require each user to have their own PDP. This can certainly be done via the API, but would be very unwieldy. A fairly simple script could retrieve a list of all users, then create and apply PDPs for each user for the given dataset. Running the script from time to time could ensure synchronization with the actual employees listed in the Domo environment, checking to see if a PDP already exists for the given user.

**Comment by ldacey** [comment]
Yep, that's what I suspected. Thanks!

**Comment by rswingler** [comment]
You're very welcome!

**Comment by ldacey** [comment]
Sorry, as I explored the UI I noticed there was a section called 'Employee #'.

```
Name
Email
Alternate email
Mobile Phone
Security Profile
Title
Employee #
```
Is it possible to add the Employee # field to the CreateUserRequest object?

```
class CreateUserRequest(DomoObject):
    accepted_attrs = [
        'name',
        'email',
        'role'
    ]
```

Then I would be able to list users and grab the Domo User ID along with the company Employee ID and easily check who exists, who needs to be removed because they aren't in our systems, etc. Looping through each row and grabbing certain values would be ideal, like below;

```
def create_domo_user(df, role):
    domo = Domo(DOMO_CLIENT, DOMO_SECRET, DOMO_API, use_https=True, logger_name='domo', logger_level=logging.ERROR)
    user_request = CreateUserRequest()
    for row in df.itertuples(index=True, name='Pandas'):
        user_request.name = getattr(row, 'employee_name')
        user_request.email = getattr(row, 'email_address')
        **user_request.employee_num = getattr(row, 'employee_id')**
        user_request.role = role
        send_invite = False
        user = domo.users.create(user_request, send_invite)
        print("Created User '{}'".format(user['name']))
```

**Comment by rswingler** [comment]
I believe extra attributes like employee number can be passed. @yunruiwatts @checketts ?

**Comment by yunruiwatts** [comment]
If you've got the latest version of the SDK, you don't need to use a `CreateUserRequest` object. You can just use a dictionary and provide it with whatever extra attributes you need.

**Comment by ldacey** [comment]
Everything is working great.  Thanks!
