### ISSUE TITLE
Exception when creating pages with API

### ISSUE THREAD

**Issue by ldacey** [domoinc/domo-python-sdk#13]
Not critical, but I was attempting to make some pages with the API and I was not successful. I noticed that there were no imports listed on the example page as well, so I attempted: 

`from pydomo import PageClient`

This seemed to work, but when I tried to create some pages:

```
domo = Domo(DOMO_CLIENT, DOMO_SECRET, DOMO_API, use_https=True, logger_name='domo', logger_level=logging.ERROR)
page = {'name': 'Telephony Dashboard'}
new_page = domo.pages.create(**page)
collections = [
        domo.pages.create_collection(new_page['id'], 'Telephony | Previous Day Performance'),
        domo.pages.create_collection(new_page['id'], 'Telephony | Week to Date Performance'),
        domo.pages.create_collection(new_page['id'], 'Telephony | Month to Date Performance'),
        domo.pages.create_collection(new_page['id'], 'Telephony | Historical Performance'),
    ]

```
I ran into this exception:

`Exception: Page Error: {"error":"insufficient_scope","error_description":"Insufficient scope for this resource","scope":"dashboard"}`

Likewise when I ran `list(domo.pages.list())`

**Comment by rswingler** [comment]
Does your API Client have "dashboard" enabled? That looks like a permissions error with the client's scope, managed on developer.domo.com: 

https://developer.domo.com/manage-clients

**Comment by ldacey** [comment]
Ah, nope. I created a new one and it works now, thanks. My initial API only had:

```
Scopes
data, user
```
