### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by CausalReinforcer** [domoinc/domo-python-sdk#18]
https://github.com/domoinc/domo-python-sdk/blob/95f9c1c79e2d0c3e1f4b1d257a82985dfdef15c7/run_examples.py#L98

NameError: `name 'Sorting'` is not defined

Changed `name 'Sorting'` to `sort='name'` and things are working as expected.

**Comment by CausalReinforcer** [comment]
In addition, I would suggest a more elegant way to hold the data:

`import pandas as pd
 pd.DataFrame(domo.datasets.list(sort='name', limit=10))`

**Comment by yunruiwatts** [comment]
I will look into the `NameError` you found.

We would love to have built-in support for pandas and other frameworks in the future. I was considering using cursors, like how pymysql and psycopg2 allow you to use different cursors to return data in different formats. So perhaps something like this?

    from pydomo.cursors import PandasCursor
    dataframe = domo.datasets.list(sort='name', limit=10, cursor=PandasCursor)

**Comment by yunruiwatts** [comment]
How are you running the examples? I did not get the `NameError` you reported. If you look at the top of the file you'll see a bunch of import statements. Did you happen to copy the file and not include all of the imports?
