### ISSUE TITLE
Dataset import and append

### ISSUE THREAD

**Issue by InfoSecured** [domoinc/domo-python-sdk#19]
Is there a way to append data using the string import in dataset management?

**Comment by yunruiwatts** [comment]
The `data_import` and `data_import_from_file` methods both support an optional `update_method`  parameter. So this should work: `data_import(dataset_id, csv_data, update_method='APPEND')`

**Comment by InfoSecured** [comment]
Great, thanks!


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC
