### ISSUE TITLE
DataSetClient references self.log and not self.logger

### ISSUE THREAD

**Issue by yalon** [domoinc/domo-python-sdk#21]
DataSetClient inherits from DomoAPIClient which initializes self.logger but it uses self.log so that raises AttributeError as can be seen in this traceback:

> 
> Traceback (most recent call last):
>   File "test/cli.py", line 167, in <module>
>     domo.load_datasets()
>   File "/Users/test/domo_target.py", line 111, in load_datasets
>     csv = self.domo.datasets.data_export(d['id'], True)
>   File "/Users/test/.virtualenvs/test/lib/python3.6/site-packages/pydomo/datasets/DataSetClient.py", line 115, in data_export
>     self.log.debug("Error downloading data from DataSet: " + self.transport.dump_response(response))
> AttributeError: 'DataSetClient' object has no attribute 'log'

**Comment by ldacey** [comment]
I saw similar behavior when trying to export data from Domo. I ended up just using the export_data_to_file function to get around it. The function below has self.log

```
    def data_export(self, dataset_id, include_csv_header):
        url = '{base}/{dataset_id}/data'.format(
                base=URL_BASE, dataset_id=dataset_id)
        response = self._download_csv(url, include_csv_header)
        if response.status_code == requests.codes.ok:
            return bytes.decode(response.content)
        else:
            self.log.debug("Error downloading data from DataSet: " + self.transport.dump_response(response))
            raise Exception("Error downloading data from DataSet: " + response.text)
```

**Comment by yunruiwatts** [comment]
@yalon thanks for catching that. I just [pushed a fix](https://github.com/domoinc/domo-python-sdk/commit/3a4e9776d52fad3ec750e2fb5cf8a054806af931), and I should be able to publish a minor update to the SDK by the end of the day.

In the future, feel free to make a pull request fixing the issue. We'd love to help the community feel like they can easily contribute to making the SDK better.
