### ISSUE TITLE
Domo won't accept schema stored as a variable

### ISSUE THREAD

**Issue by Vernboy** [domoinc/domo-python-sdk#22]
I have a script that will loop through all the files in a directory, discover their schema, create the dataset in Domo and push the data to Domo.  However, Domo's API won't accept my schema as a variable.  If I print the variable and copy and paste the result into the dsr.schema it takes it fine.  Can we change it so that it accepts the schema as a variable?

**Comment by checketts** [comment]
@Vernboy Could you include some details around the SDK version you are using and also code snippets of what is currently required and what you would expect to work?

**Comment by Vernboy** [comment]
I am using PyDomo 2.1.  Here is the relevant section of my code
`        dsr = DataSetRequest()
        dsr.name = str(allFiles[38:])
        dsr.description = 'Andrew test'
        schemaVariable = "[" + fullschema[:-2] + "]"
        print(schemaVariable)
        dsr.schema = Schema(schemaVariable)`

The code above returns the error "Exception: Error creating DataSet: {"status":400,"statusReason":"Bad Request","message":"Bad Request","toe":"UI7PGLVN12-Q56L5-9DHPR"}"  However, I know that schemaVariable is in the correct format for Domo's API because if I copy the print(schemaVariable) output and paste it in place of schemaVariable in dsr.schema = Schema(schemaVariable) then Domo accepts it.

**Comment by yunruiwatts** [comment]
@Vernboy `schemaVariable = "[" + fullschema[:-2] + "]"` suggests you're trying to give the Schema object a string instead of a list of columns. It should be easy enough to parse `schemaVariable` and turn it into a list instead of a string with `json.loads(schemaVariable)`

**Comment by Vernboy** [comment]
Thanks, that worked.  The other issue I am having - as I upload a series of files, it seems like a timeout is occurring or something.  When I upload a 10m row dataset it loads, but then my loop stops and won't go onto the next file.  Is that because of a timeout on the Domo side?

**Comment by yunruiwatts** [comment]
Can you post your loop code, as well as what you mean by the loop stopping? Is there an exception, does it hang, or does the script suddenly stop and return to the console?

**Comment by Vernboy** [comment]
Here is all my code (minus the CLIENT_ID, SECRET, API_HOST and inputdir)

`import logging
import os
import random
import re
import json
from pydomo import Domo
from pydomo.datasets import DataSetRequest, Schema, Column, ColumnType, Policy
from pydomo.datasets import PolicyFilter, FilterOperator, PolicyType, Sorting
from pydomo.users import CreateUserRequest
from pydomo.datasets import DataSetRequest, Schema, Column, ColumnType
from pydomo.streams import UpdateMethod, CreateStreamRequest
from pydomo.groups import CreateGroupRequest
from tableschema import Table


class DomoSDKExamples:
    def __init__(self):
        self.domo = self.init_domo_client(CLIENT_ID, CLIENT_SECRET)
        # self.datasets(domo)


    ############################
    # INIT SDK CLIENT
    ############################
    def init_domo_client(self, client_id, client_secret, **kwargs):
        '''
        - Create an API client on https://developer.domo.com
        - Initialize the Domo SDK with your API client id/secret
        - If you have multiple API clients you would like to use, simply initialize multiple Domo() instances
        - Docs: https://developer.domo.com/docs/domo-apis/getting-started
        '''
        handler = logging.StreamHandler()
        handler.setLevel(logging.INFO)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        logging.getLogger().addHandler(handler)

        return Domo(client_id, client_secret, logger_name='foo', log_level=logging.INFO, api_host=API_HOST, **kwargs)


    ############################
    # DATASETS
    ############################
    def sendDataset(self, schemavariable):
        '''
        DataSets are useful for data sources that only require occasional replacement. See the docs at
        https://developer.domo.com/docs/data-apis/data
        '''
        domo = self.domo
        domo.logger.info("\n**** Domo API - DataSet Examples ****\n")
        datasets = domo.datasets

        # Define a DataSet Schema
        dsr = DataSetRequest()
        dsr.name = str(allFiles[38:])
        dsr.description = 'Andrew test'      
        dsr.schema = schemavariable

        # Create a DataSet with the given Schema
        dataset = datasets.create(dsr)
        domo.logger.info("Created DataSet " + dataset['id'])

        csv_file_path = allFiles
        datasets.data_import_from_file(dataset['id'], csv_file_path, update_method='REPLACE')
        domo.logger.info("Uploaded data from a file to DataSet {}".format(dataset['id']))

for eachCSV in os.listdir(inputdir):
    schemavariable = {}
    if not eachCSV.startswith('.') and not eachCSV.endswith('.py') and os.path.isfile(os.path.join(inputdir, eachCSV)):
        allFiles = str(os.path.abspath(eachCSV))
        table = Table(allFiles)
        table.infer()
        schemaList = table.schema.descriptor
        fullschema = {"columns":[]}
        for eachDict in schemaList['fields']:
            if eachDict['type'].upper() == "BOOLEAN":
                eachDict['type'] = "STRING"
            if eachDict['type'].upper() == "NUMBER":
                eachDict['type'] = "DOUBLE"
            if eachDict['type'].upper() == "INTEGER": 
                eachDict['type'] = "DOUBLE"
            if eachDict['type'].upper() == "OBJECT": 
                eachDict['type'] = "STRING"
            myschema = {"type":eachDict['type'].upper(), "name":eachDict['name']}
            fullschema['columns'].append(myschema)
        DSE = DomoSDKExamples()   
        DSE.sendDataset(fullschema) `

I don't get any error or exception, it just seems to hang - there is nothing returned.  The big dataset fully uploads in Domo but the script doesn't move on to the next file.  If I remove the big file from the folder then it pushes through all the files no problem.  Thus it seems like a timeout to me.

**Comment by yunruiwatts** [comment]
FYI using a single backtic ` doesn't work with multi-line code blocks.

It's hard for me to tell what's going wrong without being able to see how you've got your code indented, but one thing I notice is that in the `sendDataset` method, you're using `allFiles` when it hasn't been passed in as a method parameter. It doesn't complain about it because `allFiles = str(os.path.abspath(eachCSV))` is setting it as a global variable. I'm guessing it's not the problem here, but that is something that could easily cause problems.

When you run the script and and it hangs, does it print a stack trace if you use control-c to exit the script? It would be helpful to know where the script was when it hangs. You could also add some print statements at various places (beginning of the `for` loop, beginning of `sendDataset`, etc) so that you can see better how far it's actually getting before it hangs.
