### ISSUE TITLE
'TypeError: can't concat bytes to str' when calling domo.users.update()

### ISSUE THREAD

**Issue by LawnboyMax** [domoinc/domo-python-sdk#23]
I started exploring Domo API today and having problems when calling `domo.users.update()`. Please let me know what might be causing this issue, as I think I satisfied system requirements that are listed.

**Code**

```python
import logging
from pydomo import Domo
from pydomo.users import CreateUserRequest

# Build an SDK configuration
client_id = 'my client id'
client_secret = 'my client secret'
api_host = 'api.domo.com'

# Check if connected successfully by trying to display my name
domo = Domo(client_id, client_secret, logger_name='foo', log_level=logging.INFO, api_host=api_host)
my_id = 12345678
user = domo.users.get(my_id)
print(user['name']) # correctly prints my name

# Now try changing my name
user_update = CreateUserRequest()
user_update.name = 'Max Lawnboy'
user = domo.users.update(my_id, user_update)
print(user['name'])
```

**Error Message**
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    user = domo.users.update(my_id, user_update)
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\pydomo\users\UserClient.py", line 45, in update
    return self._update(self._base(user_id), HTTPMethod.PUT, requests.codes.ok, user_update, self.userDesc)
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\pydomo\DomoAPIClient.py", line 50, in _update
    + self.transport.dump_response(response))
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\pydomo\Transport.py", line 86, in dump_response
    data = dump.dump_all(response)
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\requests_toolbelt\utils\dump.py", line 193, in dump_all
    dump_response(response, request_prefix, response_prefix, data)
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\requests_toolbelt\utils\dump.py", line 154, in dump_response
    proxy_info=proxy_info)
  File "C:\Users\user\Desktop\projects\domo_api_test\env\lib\site-packages\requests_toolbelt\utils\dump.py", line 65, in _dump_request_data
    bytearr.extend(prefix + method + b' ' + request_path + b' HTTP/1.1\r\n')
TypeError: can't concat bytes to str
```

**System Info**

Fresh virutalenv
`Python 3.6.1`
`pydomo (0.2.1)`
Windows 10, 64-bit

**Comment by yunruiwatts** [comment]
@LawnboyMax line 50 of `DomoAPIClient.py` is the second half of a line that's been split into two:

    self.logger.debug("Error updating " + obj_desc + ": "
                      + self.transport.dump_response(response))

So it looks like there was an error updating the user, but then the SDK ran into a separate issue while trying to report it.

As to why it failed to update the user, are you using a client that is tied to an admin user? Are trying to update the user the client is tied to, or a different user?

**Comment by LawnboyMax** [comment]
@yunruiwatts 
I was given an admin user account on a sandbox server just today and I created a client following [these](https://developer.domo.com/docs/authentication/quickstart-5) instructions. Yes, I am trying to update the user that I assume is tied to a client I use (I am trying to change my own user name).

**Comment by yunruiwatts** [comment]
@LawnboyMax I think you're running into one of the known limitations of the endpoint for updating users - currently it requires you to supply an email address even when it should not change. However, you should be able to use the object you received from the `get` method:

    user = domo.users.get(my_id)
    user.name = 'Max Lawnboy'
    user = domo.users.update(my_id, user)

Let me know if that doesn't work for you.

**Comment by LawnboyMax** [comment]
@yunruiwatts 
I think it should be `user['name'] = 'Max Lawnboy'`, as `user` is a `dict`. With this correction I could change my name. Thank you!

I tried using `CreateUserRequest()` and specifying the email as follows, and still get the same error:
```python
user_update = CreateUserRequest()
user_update.name = 'Max Lawnboy'
user_update.email = user['email'] # my current email
user = domo.users.update(my_id, user_update)
```
The error when executing this doesn't really matter for me at this point, since the other method works; just letting you know.

I guess `run_examples.py` and `user.py` should be updated to reflect the limitation that you mentioned

**Comment by yunruiwatts** [comment]
@LawnboyMax I'm glad you were able to get it working. You do need to set the email on the `CreateUserRequest`, but I missed that you also need to set the role as well.

`run_examples.py` and `user.py` only have one example of updating a user and it sets the user's name, role, and email; I will add a comment mentioning that those are actually required examples.

**Comment by LawnboyMax** [comment]
@yunruiwatts 
I was able to get `CreateUserRequest()` working with name, email and role specified. Thanks again.
