### ISSUE TITLE
Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by Linty101** [domoinc/domo-python-sdk#24]
Hello,

I installed Python 3 and tried to download the pydomo package with pip but got the following error.

```
$ pip install pydomo --no-cache-dir
Collecting pydomo
  Downloading pydomo-0.2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\cygwin64\tmp\pip-build-2gkndm\pydomo\setup.py", line 13, in <module>
        except FileNotFoundError as fnfe:
    NameError: name 'FileNotFoundError' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\cygwin64\tmp\pip-build-2gkndm\pydomo\
```

**Comment by yunruiwatts** [comment]
@Linty101 can you run `pip --version` and report what it says? `FileNotFoundError` should be one of the built-in errors, so I'm wondering if somehow you're not running the right version of python with your pip command.

**Comment by rswingler** [comment]
@Linty101 Also, be sure to run all commands for Python3, ie "python3 {command}" and "pip3 {command}".

**Comment by Linty101** [comment]
Hi, I had Python3 installed but not pip3. Did `apt-get python3-pip` and tried again doing `pip3 install pydomo` and it worked. Thanks for the help.
