### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by SrikanthAmudala** [domoinc/domo-python-sdk#25]
Hi, I am not able to connect. 
 Whenever I am trying to make a connection, the following error occurs. I am using Anaconda 3

  File "E:/Python projects/DOMO_Project/domo_init.py", line 17, in <module>
    domo = Domo(client_id, client_secret, api_host=api_host)
  File "E:\Anaconda3\lib\site-packages\pydomo\__init__.py", line 76, in __init__
    self.transport = DomoAPITransport(client_id, client_secret, api_host, kwargs.get('use_https', True), self.logger)
  File "E:\Anaconda3\lib\site-packages\pydomo\Transport.py", line 21, in __init__
    self._renew_access_token()
  File "E:\Anaconda3\lib\site-packages\pydomo\Transport.py", line 80, in _renew_access_token
    self.access_token = response.json()['access_token']
  File "E:\Anaconda3\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "E:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rswingler** [comment]
Hi Srikanth,

The pydomo SDK has not been tested with Anaconda. It's possible the Anaconda JSON decoder is slightly different than Python3. 

Other than that, I assume you are using "api.domo.com" as your API host? Yes?

Also, please test the pydomo initialization using plain Python3, ie 'pip3 install pydomo' and then execute using 'python3 myFile.py'. Please let us know the result of this test.

**Comment by SrikanthAmudala** [comment]
yes, I did try with plain Python 3, but no luck either I got the same error. For API_HOST I created a client under domo.developer.com and used the same ID and Secret along with the api link.

**Comment by rswingler** [comment]
What operating system are you running on your system? Also, could you post your initialization script (without your ID and Secret), as well as the bash commands you are using to execute? Thanks.

**Comment by SrikanthAmudala** [comment]
I tried both on windows10 and macOS but still got the same error. Please find the attached screenshot. Thanks!

![error_1](https://user-images.githubusercontent.com/28958273/36497389-3fc6f8a8-1761-11e8-9304-0e5b162d7d12.PNG)

Here is where the error occurred, I have tried printing the response status and it's 200

![error_loc](https://user-images.githubusercontent.com/28958273/36497596-c5e00c9a-1761-11e8-9b0e-a2d30c8e9289.PNG)

**Comment by rswingler** [comment]
Is your API host "api.domo.com" ?

**Comment by rswingler** [comment]
Also, please print "response.text" off of line 80 in Transport.py. We are looking into possible causes of the error.

**Comment by SrikanthAmudala** [comment]
yes, the response is in HTML format. Tried to pass through json.dumps() but the same error occurred again
<img width="1156" alt="screen shot 2018-02-22 at 1 12 10 am" src="https://user-images.githubusercontent.com/28958273/36501680-c06a98e6-176d-11e8-8732-99ba9e5ff90a.png">

**Comment by rswingler** [comment]
Your API host appears to be incorrect. Is your API_HOST "api.domo.com"?

**Comment by SrikanthAmudala** [comment]
My bad, I replaced my hostname in place of API. it Worked now. Thanks a lot, I am working on Anaconda 3, So the SDK works on Anaconda as well. Thanks again!

**Comment by rswingler** [comment]
You're very welcome!
