### ISSUE TITLE
Stream API List Executions method ignores limit and offset params

### ISSUE THREAD

**Issue by RyanWilsonBIBend** [domoinc/domo-python-sdk#26]
If you get lists of executions for a stream with a few different values for limit and offset you can see they all return the same list regardless of what limit/offset params you put in

**Comment by yunruiwatts** [comment]
Thanks for reporting this. We'll take a look!

**Comment by yunruiwatts** [comment]
We found the issue - the parameters end up getting ignored by the system. I'll update this issue once we've rolled out the fix.

**Comment by RyanWilsonBIBend** [comment]
FYI this was fixed with the Domo update around July 19, 2018
