### ISSUE TITLE
Delete a specific Execution ID

### ISSUE THREAD

**Issue by ldacey** [domoinc/domo-python-sdk#27]
Would it be feasible to add an API feature that would delete a specific Execution ID? I can list them, and abort specific ones, but I can only delete one through the web interface (history page, but it is not labeled).

In certain cases I would prefer to use 'append' datasets instead of 'replace'. My workaround is to send parts over and then committing the execution when the parts have been loaded, but it is wasteful in some cases where I only need to replace a few calendar dates of data and not entire months or a year.

```
[{'createdAt': '2018-05-11T18:26:28Z',
  'currentState': 'SUCCESS',
  'endedAt': '2018-05-11T18:26:37Z',
  'id': 1,
  'modifiedAt': '2018-05-11T18:26:37Z',
  'startedAt': '2018-05-11T18:26:28Z',
  'updateMethod': 'APPEND'},
 {'createdAt': '2018-05-11T18:26:44Z',
  'currentState': 'SUCCESS',
  'endedAt': '2018-05-11T18:26:54Z',
  'id': 2,
  'modifiedAt': '2018-05-11T18:26:54Z',
  'startedAt': '2018-05-11T18:26:44Z',
  'updateMethod': 'APPEND'},
```

I think that it would be helpful to associate each Execution ID with a calendar date in my workflow. If I rerun tasks for that date, I would be able to delete the associated Execution ID, and then replace the data for just that date as a new execution.

**Comment by rswingler** [comment]
It sounds odd, but making small updates is currently a very difficult problem to solve.  This feature should absolutely exist, but we are not there yet. The Domo engine is designed to accept, standardize, and  _combine_ any amount of data from _hundreds_ of possible sources. We're always building it.

With that said, the API is just an extension of the product's current capabilities. Also, I understand the Execution suggestion - it would be nice to manage/update a large DataSet in slices. However, Executions are simply a record of an upload job, and don't bear any weight once they have been completed. 

In the future, I believe we will have a way of updating DataSets that would resemble a database UPDATE operation (specifying rows by ID or values). Don't quote me on that, but it makes perfect sense to have the ability to make small updates.
