### ISSUE TITLE
Run_Examples exampe: pages link in docstring lead to 404

### ISSUE THREAD

**Issue by ssikdar-r7** [domoinc/domo-python-sdk#28]
https://github.com/domoinc/domo-python-sdk/blob/master/run_examples.py

In the docstring of function pages:

def pages(self, domo):
        '''Page Docs: https://developer.domo.com/docs/domo-apis/pages
        '''

This link when put into the browser leads to a 404.

Curl example:

$ curl -I https://developer.domo.com/docs/domo-apis/pages
HTTP/2 404 
server: nginx/1.13.7
date: Mon, 21 May 2018 15:10:49 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
set-cookie: SESS10694d8e4f0d8a48662661b2ab8039f7=7d51703215357c3d4dd8d64e42577ec8; expires=Mon, 21-May-2018 15:10:48 GMT; Max-Age=0
set-cookie: SSESS10694d8e4f0d8a48662661b2ab8039f7=5908eefd674b6cd0c7242ea43b234b03; path=/; domain=.developer.domo.com; secure; HttpOnly
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
link: <https://developer.domo.com/wp-json/>; rel="https://api.w.org/"
strict-transport-security: max-age=15724800; includeSubDomains;

Thanks!

**Comment by murphysean** [comment]
I'm guessing it is supposed to point to: https://developer.domo.com/docs/page-api-reference/page, I'm going to update that real quick
