### ISSUE TITLE
The max amount of users to return in the list 500

### ISSUE THREAD

**Issue by mpoudel0313** [domoinc/domo-python-sdk#31]
Limiting the max numbers of users to return in the list to 500 is very inconvenient.  We are planning to automate some of the user management through python and we have more than 800 users  and this makes it very difficult for us to fully automate.

Are you guys planning on increasing this in the future?

**Comment by yunruiwatts** [comment]
We do not plan on increasing this, but at some point in the future we may change the `users.list` method to make the multiple API calls automatically. You should be able to manually call the API multiple times, each time increasing the offset, for example:

    users = domo.users.list(500, 0)
    users += domo.users.list(500, 500)
