### ISSUE TITLE
pydomo get error

### ISSUE THREAD

**Issue by BruceP99166** [domoinc/domo-python-sdk#36]
Good day.  I'm using the datasets.data_import api to upload records into a Domo dataset.  When I ran the update, it appeared to run successfully, but the dataset was not changed.  How can I trap the error from datasets.data_import?

Thanks in advance for your attention.

**Comment by murphysean** [comment]
Any problems that occur during the execution of one of the python functions is raised as an exception, and can be caught and handled as such.

Inside the GET: https://github.com/domoinc/domo-python-sdk/blob/master/pydomo/DomoAPIClient.py#L33

However this might be more an issue of the timing of the operations, once a "changeset" is uploaded to a dataset it can take awhile for the system to process it, most are reflected immediately as we are pretty good at processing, but we state up to ~15m being the normal, but it could take longer in the case of system issues.

We are working on offering clients a way to determine when a dataset is updated and query-able after a transaction via the api.

Hope that helps
