### ISSUE TITLE
Limit of user that can be pulled per group

### ISSUE THREAD

**Issue by mpoudel0313** [domoinc/domo-python-sdk#37]
I was wondering is there a  limit on how many users can you pull per group. Currently we have several groups that has more than 50 users but when I try to pull the list of users per each group, it only pulls only 50 users for that group. 

 Here is the script below:

**Comment by mpoudel0313** [comment]
get_group = domo.groups.list(100,0)
        group_list = []
        for x in get_group:
            grp = {}
            grp['name'] = x['name']
            grp['id'] = x['id']
            grp['users'] = domo.groups.list_users(x['id'])
            group_list.append(grp)
        print(group_list)

**Comment by mpoudel0313** [comment]
Any update on this?

**Comment by rswingler** [comment]
I apologize for the delay, and thank you for pointing this out. I will need to add a limit/offset to the "list_users()" function in the GroupClient. I've started working on the update.

To answer your question - the default limit for most lists is 50, and the maximum is 500.

**Comment by mpoudel0313** [comment]
Thank you.

**Comment by rswingler** [comment]
I've added the limit and offset to the 'groups.list_users' function; it now behaves as any other listing function in the SDK:
```
id = 'foo'
limit = 500
offset = 0
users = domo.groups.list_users(id, limit, offset)
```

The latest SDK version is now v0.2.3. You can upgrade your pydomo package via
```
pip3 install pydomo --upgrade
```

**Comment by mpoudel0313** [comment]
Thanks a lot. Much appreciated.

**Comment by rswingler** [comment]
You're very welcome!
