### ISSUE TITLE
Example script fails on export

### ISSUE THREAD

**Issue by tslamparter** [domoinc/domo-python-sdk#38]
I've been using DOMO for 6 months now and I want to learn python so I'm making this my first project. When I run the example script (with my api credentials), it successfully creates a dataset in my instance and updates it, but seems to fail on export. Since I just started with Python, I'm not sure what the problem is.
[run data.txt](https://github.com/domoinc/domo-python-sdk/files/3160110/run.data.txt)

**Comment by rswingler** [comment]
Python is a great language to get started with. Thank you for the stack trace; it's possible the SDK is out of sync with one of the underlying services - they change frequently. I also saw some rate limiting errors in the trace. I'll dig into this first thing tomorrow morning.

**Comment by murphysean** [comment]
I'm going to close out this issue, feel free to let us know if it continues to be an issue.
