### ISSUE TITLE
Domo Connection Issue 

### ISSUE THREAD

**Issue by mpoudel0313** [domoinc/domo-python-sdk#41]
Hi, 
I am trying to run the script through Python and now it is giving this error. It was working fine few days prior. Any Ideas why this error is coming up.

SSLError: HTTPSConnectionPool(host='api.domo.com', port=443): Max retries exceeded with url: /oauth/token?grant_type=client_credentials (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by murphysean** [comment]
This looks like it could have been an intermittent issue, either with the client or servers. I've seen this in some of the other SDKs. If you are still facing this issue, let's re-open and coordinate.
