### ISSUE TITLE
'Domo' has no attribute 'ds_create'

### ISSUE THREAD

**Issue by haiyingying** [domoinc/domo-python-sdk#55]
Hi, I am trying to upload a panda dataset to DOMO using ds_create but it returns that the domo object has no attribute 'ds_create' that I could use.

my domo is like: 
domo = Domo(client_id, client_secret, api_host=api_host, logger_name=logger_name, log_level=log_level)

and I am trying to create a dataset and upload it to DOMO:
domo.ds_create(Output,'Python | historical data','Python | Generated during demo')

Thankss!

**Comment by jeremydmorris** [comment]
Just to be sure you're on the right version, could you comment with the results of the following command?

pip show pydomo

**Comment by haiyingying** [comment]
Name: pydomo
Version: 0.3.0
Summary: The official Python3 Domo API SDK - Domo, Inc.
Home-page: https://github.com/domoinc/domo-python-sdk
Author: Bobby Swingler
Author-email: bobby.swingler@domo.com
License: MIT
Location:
Requires: requests, requests-toolbelt
Required-by:

**Comment by jeremydmorris** [comment]
Hmmm. You have the right version installed. I can't reproduce the issue on my local machine. Are you maybe using a virtual environment with the old version installed?

One other question, is the "Output" object a pandas dataframe? I think that might also cause this error.

**Comment by jeremydmorris** [comment]
> Hmmm. You have the right version installed. I can't reproduce the issue on my local machine. Are you maybe using a virtual environment with the old version installed?
> 
> One other question, is the "Output" object a pandas dataframe? I think that might also cause this error.

Sorry, just re-read the issue and it looks like you have confirmed that it is a pandas dataframe. The only additional thing I can think of is to have you copy the error here verbatim so I can do some research. Since I can't reproduce the error locally, I'm having a hard time knowing where to go next.

**Comment by haiyingying** [comment]
Magically, I tried domo.ds_create(df_up=xxx,name='xxx') today and it is working now! Many thanks !!!

**Comment by jeremydmorris** [comment]
That's great!! I wonder what happened? Quick note, I made a few more adjustments and released a new version yesterday. I fixed the ds_query function and a lot of the group functions. Detailed notes can be found in the release notes.

**Comment by jeremydmorris** [comment]
That's great!! I wonder what happened? Quick note, I made a few more adjustments and released a new version yesterday. I fixed the ds_query function and a lot of the group functions. Detailed notes can be found in the release notes.
