### ISSUE TITLE
ds_query returning status 400

### ISSUE THREAD

**Issue by christopherPMello** [domoinc/domo-python-sdk#62]
I am having an issue with ds_query. When running the following query, I get an error (status code 400). 

**Query**: 
data_set_id = '**********'
query = {"sql": "SELECT * FROM table LIMIT 2"}
ds = domo.ds_query(data_set_id, query)

**Error:**
{"status":400, "statusReason":"BadRequest","message":"Cannot deserialize instance of java.lang.String out of START_OBJECT token"}.

ds_get works fine and returns data as expected.

**Comment by jeremydmorris** [comment]
Try the call with just the query. The ds_query function structures the rest of the request for you.

**Comment by christopherPMello** [comment]
Thank you for getting back to me. 
I tried the call without the dataset id as such: 

**Query:**
domo = Domo(CLIENT_ID, SECRET, api_host='api.domo.com')
query = {"sql": "SELECT * FROM TABLE LIMIT 2"}
ds = domo.ds_query(query)

**Error:**
ds_query() missing 1 required positional argument: 'query'

Is that what you meant by trying with just the query?

**Comment by christopherPMello** [comment]
Thank you for the help! That worked!
