### ISSUE TITLE
Stream upload_part question.

### ISSUE THREAD

**Issue by FloobtheGreat** [domoinc/domo-python-sdk#7]
Should the following example from pydomo.streams raise an error when an upload fails(i.e. server refuses connection etc.)? Only having a problem when multi-threading uploads. My test streams are arriving short of data and no exceptions are popping up.

execution = streams.upload_part(stream.id, execution.id, part, csv)

If this is something that should be taken up with the Support team, let me know.

Phillip Irwin
Bass Pro Shops

**Comment by rswingler** [comment]
All of the pydomo functions raise an exception when the API request fails, ie a non-200 response. The upload_part() function calls _upload_csv() which follows this behavior:
```
    def _upload_csv(self, url, success_code, csv, obj_desc):
        response = self.transport.put_csv(url=url, body=csv)
        if response.status_code == success_code:
            if str(response.text) == '':
                return
            else:
                return self.transport.json_to_obj(response.text)
        else:
            raise Exception("Error uploading " + str(obj_desc) + ": " + self.transport.dump_response(response))
```
With that in mind, the loss of data may be on the API side. Please log the response objects from your part uploads and post them here. We will run some tests against the API.
@yunruiwatts

**Comment by yunruiwatts** [comment]
@FloobtheGreat seeing as you're only having trouble when multi-threading uploads, can you share your upload code? There are a handful of things that could be going wrong, so having that code would be very helpful for us to diagnose/reproduce the issue.

**Comment by FloobtheGreat** [comment]
Looking into the logs as you suggested allowed me to pinpoint that my problem was actually on the data read side. Specifically, trying to use pandas.read_sql asynchronously, being a blocking process.
I'm including the asynchronous uploading code here for posterity. Thanks for the help!

` def uploadPart(self, arglist):            
        for i in range(5):
                try:
                    
                    execution = self.streams.upload_part(arglist[0], arglist[1],arglist[2], csv = open(arglist[3], 'rb'))
                    
                    if execution is not None:
                        self.logger.info('Response: ' + str(execution))
                        
                except Exception as e:
                    self.logger.error(e)
                    #logging.warning(str(arglist[2]) + ' Failed on part ' + str(arglist[3]) + '... retrying in 5 sec')
                    time.sleep(5)
                    continue
                break    
        
    def uploadStream(self, execution, stream, filelist):
        self.logger.info('Starting Upload')
        t = time.time()
        i = 0
        args = list()
        for file in filelist:
            i+=1
            args.append([stream.id, execution.id, i, file])
    
        
                
        async def upload(self, args):
        
            with concurrent.futures.ThreadPoolExecutor(max_workers=24) as executor:
          
                loop = asyncio.get_event_loop()
                futures = [
                    loop.run_in_executor(
                        executor, 
                        self.uploadPart,
                        arg
                    )
                    for arg in args
                ]
                for response in await asyncio.gather(*futures):
                    pass
        
        try:
            loop = asyncio.get_event_loop()
            loop.run_until_complete(upload(self, args))
        except Exception as e:
            self.logger.error(e)
        
            
        self.streams.commit_execution(stream.id, execution.id)
        self.logger.info('Completed Stream Upload in ' + str(time.time()-t) + ' secs...')`
