### ISSUE TITLE
GZIP support

### ISSUE THREAD

**Issue by meeeller** [domoinc/domo-python-sdk#8]
The API only supports CSV files...is there going to be support for GZIP filese?

From the Domo website:
Note: Streams support gzip compression; all CSV data parts should be uploaded as gzip files (application/gzip). This will greatly reduce upload time. Plain CSV uploads are also supported, but are only recommended for very small DataSets.

A part should be no smaller than 20MB and no larger than 100MB of data

**Comment by rswingler** [comment]
The Streams API accepts compressed csv files (zip, gzip): https://developer.domo.com/docs/domo-apis/stream-apis#Data%20Preparation

The DataSet API does not. Which API are you referring to?

**Comment by meeeller** [comment]
Referring to the python API for the StreamClient.py.  It only has CSV
headers.  The API reference says headers have to be Content-Type:
application/gzip

From:
https://developer.domo.com/docs/data-apis/stream-apis#API%20-%20Upload%20a%20Part


Code:

    def upload_part(self, stream_id, execution_id, part_num, csv):
        url = self._base(stream_id) + '/executions/' + str(execution_id) +
'/part/' + str(part_num)
        desc = "Data Part on Execution " + str(execution_id) + " on Stream
" + str(stream_id)
        return self._upload_csv(url, requests.codes.ok, csv, desc)

Uses:

def put_csv(self, url, body):
        return self.request(url, HTTPMethod.PUT, self._headers_send_csv,
{}, body)

    def _headers_send_csv(self):
        headers = self._headers_default_receive_json()
        headers['Content-Type'] = 'text/csv'
        return headers

Thanks,
-Matt


*Matthew Miller*
Director of Business Analytics, Spredfast Inc.
E mmiller@spredfast.com P (512) 826-0493 <(512)%826-0493>
Spredfast on Twitter <http://twitter.com/Spredfast> | Facebook
<http://www.facebook.com/Spredfast> | Blog
<https://www.spredfast.com/social-marketing-blog>

**Comment by meeeller** [comment]
Not seeing file support for streams either in the SDK. In-mem .CSV only for the SDK?

**Comment by ldacey** [comment]
Hi - I am facing the same issue. I have tried to upload a part from a gzip file (wb, and wt) but ran into errors. I also run into an error if I try to point to the filename/path.

with gzip.open('output.csv.gz', 'wt', encoding='utf-8') as outfile:
    cur.copy_expert( sql.format(query), outfile)

TypeError: descriptor 'encode' requires a 'str' object but received a '_io.TextIOWrapper'
```

```
with gzip.open('output.csv.gz', 'wt', encoding='UTF-8') as outfile:
    cur.copy_expert( sql.format(query), outfile)

TypeError: descriptor 'encode' requires a 'str' object but received a '_io.TextIOWrapper'


`
Exception: Error uploading Data Part on Execution 9999 on Stream 9999: {"status":400,"statusReason":"Bad Request","message":"Invalid CSV provided during upload. msg=There are too few columns. Expected 23. Row 1, column 2. Row: /output.csv.gz\n","toe":"8T5"}`

**Comment by rswingler** [comment]
I apologize for the hiatus; this project changed hands. I've merged the solution written by @ldacey; the latest version of the SDK has gzip support. 

You can update your PyDomo package via `pip3 install pydomo --upgrade`
