### ISSUE TITLE
Support `request_timeout` on token renewal HTTP request

### ISSUE THREAD

**Issue by gc-jeremy** [domoinc/domo-python-sdk#85]
Hello,

Would it be possible to use `self.request_timeout` in the requests call in `DomoApiTransport._renew_access_token()`?

https://github.com/domoinc/domo-python-sdk/blob/master/pydomo/Transport.py#L88

**Comment by samrands** [comment]
@gc-jeremy This has been released in v0.3.0.7 (https://pypi.org/project/pydomo/). Thanks for helping make the Domo Python SDK better!

**Comment by gc-jeremy** [comment]
@samrands - Thank you!
