### ISSUE TITLE
How do I update a data set through the API?

### ISSUE THREAD

**Issue by fmv1992** [domoinc/domo-python-sdk#87]
How do I update a data set? It is not clear from the current docs. To be explicit:

* * *
![image](https://user-images.githubusercontent.com/15706854/214298651-5e237eeb-3d9d-43a1-ad47-442610c6aca7.png)

* * *

Thanks.

**Comment by fmv1992** [comment]
@nathan-pilling-domo (I'm not sure who else to tag),

This would be very handy. It would enable for a better integration with Apache Airflow for instance.

**Comment by thattolleyguy** [comment]
@fmv1992 There are many ways to update a dataset. Looking at the screenshot you provided, the dataset you're referencing is a connector dataset which should have a schedule configured in the dataset settings. The dataset should automatically update at the scheduled frequency. Clicking the run now button can trigger a manual run of the update process and that should also update the dataset.

With other datasets you can use the CLI, API or SDKs to update them. For general questions like this, I would recommend reaching out to domo support for a quicker response in the future.

**Comment by thattolleyguy** [comment]
I just re-read your comment and saw you mentioned apache airflow. You should be able to use the python sdk within apache airflow. Look for the ds_update method. More information is in the README.
