### ISSUE TITLE
Requesting asynchronously

### ISSUE THREAD

**Issue by eoghantelnyx** [domoinc/domo-python-sdk#9]
Any plans to use aiohttp or something similar to enable usage of this library in async tasks?

**Comment by meeeller** [comment]
Pro Tip: Ask your Domo rep for the Java CLI.  I wasted many weeks trying to use the Python SDK and trying to work with what they have publicly stated their API is (the documentation is on v1 and I think there is at least a v3).  

I was trying to write stuff to chunk and gzip files.   After burning consulting time with Domo they gave me a CLI written in Java, that does all the async chunking and uploading.  They basically laughed at me for trying to use the domo-python-sdk.  Pretty frustrating experience.

Hope this helps. -Matt

Commands:
  help               Displays this command
  connect            Connects to a Domo server
  disconnect         Disconnects from the Domo server
  create-user        Creates a Domo user
  create-datasource  Creates a Domo datasource
  delete-datasource  Deletes a Domo datasource
  derive-schema      Derives a datasource schema from an input file
  define-upsert      Defines dataset upsert columns
  search-domo        Searches Domo by entity type & search term. Valid entities are page, card, user, group & dataset
  move-page          Moves pages in navigation hierarchy
  list-datasource    Lists Domo datasources
  generate-card-image  Generates a card image
  rename-fusion-columns  Renames data fusion columns
  upload-datasource  Uploads data to a Domo datasource
  upload-redshift    Uploads data to Domo from a Redshift unload query
  data-import        Start Domo datasources
  data-split         Takes a single input CSV file and splits it into individual GZipped parts
  rename-card        Renames a card by id
  export-data        Exports dataset to a CSV file
  query-data         Queries dataset and writes results to a CSV file
  whoami             Displays the current user identity from the Domo server
  watch              Creates a new process that watches a given file or directory and uploads data to domo
  kill-watcher       Kills directory watcher process with given id
  quit               Quits the application

**Comment by checketts** [comment]
@meeeller Please don't hijack issues. I appreciate you trying to offer the quickest path, but I would rather have specific issues filed that make the SDK easier to work with.

**Comment by yunruiwatts** [comment]
@eoghantelnyx Based on https://stackoverflow.com/questions/43241221/how-can-i-wrap-a-synchronous-function-in-an-async-coroutine, it looks like you should be able to use the event loop's `run_in_executor` to make SDK calls from async tasks. You could use either a `ThreadPoolExecutor`  or a `ProcessPoolExecutor`, but given that the SDK calls are likely to be IO bound I would suggest starting with a `ThreadPoolExecutor`.

While we haven't done rigorous testing on it, I believe all the SDK commands are thread-safe.
