### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by Ethan1296** [domoinc/domo-python-sdk#96]
Hi. We couldn't interact with domo via api in both Python and R yesterday,  we created a new client id and secret, but it still doesn't work.
![error](https://github.com/domoinc/domo-python-sdk/assets/128681856/54e2d5fa-7d91-4418-adde-5a5b5d744278)

**Comment by samrands** [comment]
Do you mind getting in touch with support and having them create a ticket for us? Thanks @Ethan1296 .

**Comment by Ethan1296** [comment]
Thank you, I will contact with them.
